### PR TITLE
Upgrade vault, traefik; run zerotier in docker host network

### PR DESCRIPTION
**Pull request by jojomomojo**
- upgrade vault to 1.5.0
- upgrade traefik to 2.2.7
- zerotier runs in docker vm to provide zerotier to default bridge network
- remove dc0, hardcoded host and kitt network numbers
- remove unbound, let user configure upstream dns servers for pihole
- /service.d hooks for pihole, zerotier

### CODE REVIEW

**Comment by jojomomojo** [comment]
@bellaweo there's a `KITT_DOCKER_NETWORK` that is a cidr for what network you want for the kitt network.  I might need to use it to assign static IPs to the kitt servers.  Makes it easier to generate static configuration if the services don't change IPs every time they come up.  Not sure if I can use `KITT_DOCKER_NETWORK` the way I want.

**Comment by jojomomojo** [comment]
@bellaweo do you mean the network in `daemon.json`?  That just generates a file, up to you to put it in the right place, edit, and reload Docker.  Not a bad default, close to what Docker uses.

**Comment by bellaweo** [comment]
since kitt would run on multiple hosts and they could have any number of docker setups (outside of kitt), I am wondering if we should rely on docker to set the kitt newtwork ip range (to avoid conflicts and errors). we can always add a `docker network inspect kitt` to get that assigned range and from there, add any number of static IP addresses.

**Comment by jojomomojo** [comment]
@bellaweo let me see what it takes to assign a static IP -- that will determine if we can use a dynamic network.  Letting Docker choose the network won't help with conflicts between multiple hosts -- no coordination between Docker to know who is using what.  This is what consul's wan federation via gateway meshes is supposed to help with: connect different datacenters with conflicting network.

**Comment by jojomomojo** [comment]
@bellaweo I read multiple hosts wrong, the conflict can come from an existing use of the kitt network for non-kitt purposes.

**Pull request merged**
